return {
    idle = {
        Vector2.new(3, 3);
    };
    alert = {
        Vector2.new(7, 3);
    };
    scratchSelf = {
        Vector2.new(5, 0);
        Vector2.new(6, 0);
        Vector2.new(7, 0);
    };
    scratchWallN = {
        Vector2.new(0, 0);
        Vector2.new(0, 1);
    };
    scratchWallS = {
        Vector2.new(7, 1);
        Vector2.new(6, 2);
    };
    scratchWallE = {
        Vector2.new(2, 2);
        Vector2.new(2, 3);
    };
    scratchWallW = {
        Vector2.new(4, 0);
        Vector2.new(4, 1);
    };
    tired = {
        Vector2.new(3, 2);
    };
    sleeping = {
        Vector2.new(2, 0);
        Vector2.new(2, 1);
    };
    N = {
        Vector2.new(1, 2);
        Vector2.new(1, 3);
    };
    NE = {
        Vector2.new(0, 2);
        Vector2.new(0, 3);
    };
    E = {
        Vector2.new(3, 0);
        Vector2.new(3, 1);
    };
    SE = {
        Vector2.new(5, 1);
        Vector2.new(5, 2);
    };
    S = {
        Vector2.new(6, 3);
        Vector2.new(7, 2);
    };
    SW = {
        Vector2.new(5, 3);
        Vector2.new(6, 1);
    };
    W = {
        Vector2.new(4, 2);
        Vector2.new(4, 3);
    };
    NW = {
        Vector2.new(1, 0);
        Vector2.new(1, 1);
    };
}